name: 'Generate DNSBL'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '8 0 * * *'

jobs:
  scan:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python and pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install requirements for et2dns
      run: pip install -r requirements.txt
    - name: Download ET Open Suricata 5 rules
      run: bash fetch_et_open.sh
    - name: Generate DNSBL from ET Open rules
      run: python3 et2dns.py --rules emerging-all.suricata5.rules
    - name: Copy artisanal index file
      run: cp misc/index.html output/
    - name: Sync to BunnyCDN Edge
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: storage.bunnycdn.com
        ftp_username: emerging-threats-dnsbl
        ftp_password: ${{ secrets.BUNNY_FTP_PASSWORD }}
        local_source_dir: "./output/."
        dist_target_dir: ""
        delete: "true"
        exclude: "'^.git/' '^.github/' '^README.md' '^LICENSE'"
        disable_ssl_certificate_verification: false